# Generated by Django 5.2.7 on 2025-10-03 00:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='estrellas',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='juego',
            name='imagen',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
