# Generated by Django 5.2.8 on 2025-11-07 00:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='juego',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
