# Generated by Django 5.2.8 on 2025-11-27 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_juego_creado_en_alter_juego_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='desarrollador',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='juego',
            name='genero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='juego',
            name='plataforma',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
